name: geochem
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - anyio=4.3.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - aws-c-auth=0.7.17
  - aws-c-cal=0.6.11
  - aws-c-common=0.9.15
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.7
  - aws-c-mqtt=0.10.3
  - aws-c-s3=0.5.7
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.6
  - aws-sdk-cpp=1.11.267
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - brotli-python=1.1.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - cctools_osx-64=986
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - clang=18.1.3
  - clang-18=18.1.3
  - clang_impl_osx-64=18.1.3
  - clang_osx-64=18.1.3
  - clangxx=18.1.3
  - clangxx_impl_osx-64=18.1.3
  - clangxx_osx-64=18.1.3
  - comm=0.2.2
  - compiler-rt=18.1.3
  - compiler-rt_osx-64=18.1.3
  - curl=8.7.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - gfortran_impl_osx-64=12.3.0
  - gfortran_osx-64=12.3.0
  - glog=0.7.0
  - gmp=6.3.0
  - graphite2=1.3.13
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=8.3.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - isl=0.26
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - json5=0.9.25
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.1.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.26.0
  - krb5=1.21.2
  - ld64_osx-64=711
  - lerc=4.0.0
  - libabseil=20240116.1
  - libarrow=14.0.2
  - libarrow-acero=14.0.2
  - libarrow-dataset=14.0.2
  - libarrow-substrait=14.0.2
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp18.1=18.1.3
  - libcrc32c=1.1.2
  - libcurl=8.7.1
  - libcxx=16.0.6
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran-devel_osx-64=12.3.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libgoogle-cloud=2.22.0
  - libgoogle-cloud-storage=2.22.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm18=18.1.3
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libparquet=14.0.2
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libwebp-base=1.4.0
  - libxml2=2.12.6
  - libzlib=1.2.13
  - llvm-openmp=18.1.3
  - llvm-tools=18.1.3
  - lz4-c=1.9.4
  - make=4.3
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - nbclient=0.10.0
  - nbconvert-core=7.16.3
  - nbformat=5.10.4
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - nlopt=2.7.1
  - notebook=7.1.3
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openssl=3.2.1
  - orc=2.0.0
  - overrides=7.7.0
  - packaging=24.0
  - pandoc=3.1.13
  - pandocfilters=1.5.0
  - pango=1.52.1
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.22
  - pygments=2.17.2
  - pyobjc-core=10.2
  - pyobjc-framework-cocoa=10.2
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.0
  - r-abind=1.4_5
  - r-arrow=14.0.1
  - r-askpass=1.2.0
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.3.3
  - r-base64enc=0.1_3
  - r-bayesm=3.1_6
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-blob=1.2.4
  - r-boot=1.3_30
  - r-broom=1.0.5
  - r-bslib=0.7.0
  - r-cachem=1.0.8
  - r-callr=3.7.6
  - r-car=3.1_2
  - r-cardata=3.0_5
  - r-caret=6.0_94
  - r-cellranger=1.1.0
  - r-class=7.3_22
  - r-cli=3.6.2
  - r-clipr=0.8.0
  - r-clock=0.7.0
  - r-cluster=2.1.6
  - r-codetools=0.2_20
  - r-colorspace=2.1_0
  - r-commonmark=1.9.1
  - r-compositions=2.0_8
  - r-conflicted=1.2.0
  - r-conquer=1.3.3
  - r-corrplot=0.92
  - r-cowplot=1.1.3
  - r-cpp11=0.4.7
  - r-crayon=1.5.2
  - r-crosstalk=1.2.1
  - r-crul=1.4.2
  - r-curl=5.1.0
  - r-data.table=1.15.2
  - r-dbi=1.2.2
  - r-dbplyr=2.4.0
  - r-dendextend=1.17.1
  - r-deoptimr=1.1_3
  - r-diagram=1.6.5
  - r-digest=0.6.35
  - r-dplyr=1.1.4
  - r-dt=0.33
  - r-dtplyr=1.3.1
  - r-e1071=1.7_14
  - r-ellipse=0.5.0
  - r-ellipsis=0.3.2
  - r-emmeans=1.10.1
  - r-essentials=4.3
  - r-estimability=1.4.1
  - r-evaluate=0.23
  - r-factoextra=1.0.7
  - r-factominer=2.10
  - r-fansi=1.0.6
  - r-farver=2.1.1
  - r-fastmap=1.1.1
  - r-flashclust=1.01_2
  - r-fontawesome=0.5.2
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-foreign=0.8_86
  - r-formatr=1.14
  - r-fs=1.6.3
  - r-future=1.33.2
  - r-future.apply=1.11.2
  - r-gargle=1.5.2
  - r-generics=0.1.3
  - r-ggplot2=3.5.0
  - r-ggpubr=0.6.0
  - r-ggrepel=0.9.5
  - r-ggsci=3.0.3
  - r-ggsignif=0.6.4
  - r-ggtern=3.5.0
  - r-gistr=0.9.0
  - r-glmnet=4.1_8
  - r-globals=0.16.3
  - r-glue=1.7.0
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gower=1.0.1
  - r-gridextra=2.3
  - r-gtable=0.3.4
  - r-hardhat=1.3.1
  - r-haven=2.5.4
  - r-hexbin=1.28.3
  - r-highr=0.10
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpcode=0.3.0
  - r-httpuv=1.6.15
  - r-httr=1.4.7
  - r-ids=1.0.1
  - r-ipred=0.9_14
  - r-irdisplay=1.1
  - r-irkernel=1.3.2
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.8
  - r-kernsmooth=2.23_22
  - r-knitr=1.46
  - r-labeling=0.4.3
  - r-later=1.3.2
  - r-latex2exp=0.9.6
  - r-lattice=0.22_6
  - r-lava=1.7.3
  - r-lazyeval=0.2.2
  - r-leaps=3.1
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-lme4=1.1_35.3
  - r-lobstr=1.1.2
  - r-lubridate=1.9.3
  - r-magrittr=2.0.3
  - r-maps=3.4.2
  - r-maptools=1.1_8
  - r-mass=7.3_60
  - r-matrix=1.6_5
  - r-matrixmodels=0.5_3
  - r-matrixstats=1.3.0
  - r-memoise=2.0.1
  - r-mgcv=1.9_1
  - r-mime=0.12
  - r-minqa=1.2.6
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.11
  - r-multcompview=0.1_10
  - r-munsell=0.5.1
  - r-mvtnorm=1.2_4
  - r-nlme=3.1_164
  - r-nloptr=2.0.3
  - r-nnet=7.3_19
  - r-numderiv=2016.8_1.1
  - r-openssl=2.1.1
  - r-parallelly=1.37.1
  - r-pbdzmq=0.3_11
  - r-pbkrtest=0.5.2
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-plyr=1.8.9
  - r-polynom=1.4_1
  - r-prettyunits=1.2.0
  - r-proc=1.18.5
  - r-processx=3.8.4
  - r-prodlim=2023.08.28
  - r-progress=1.2.3
  - r-progressr=0.14.0
  - r-promises=1.3.0
  - r-proto=1.0.0
  - r-proxy=0.4_27
  - r-pryr=0.1.6
  - r-ps=1.7.6
  - r-purrr=1.0.2
  - r-quantmod=0.4.26
  - r-quantreg=5.97
  - r-r.methodss3=1.8.2
  - r-r.oo=1.26.0
  - r-r.utils=2.12.3
  - r-r6=2.5.1
  - r-ragg=1.3.0
  - r-randomforest=4.7_1.1
  - r-rappdirs=0.3.3
  - r-rbokeh=0.5.2
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.12
  - r-rcpparmadillo=0.12.8.2.1
  - r-rcppeigen=0.3.4.0.0
  - r-readr=2.1.5
  - r-readxl=1.4.3
  - r-recipes=1.0.10
  - r-recommended=4.3
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-repr=1.1.7
  - r-reprex=2.1.0
  - r-reshape2=1.4.4
  - r-rio=1.0.1
  - r-rlang=1.1.3
  - r-rmarkdown=2.26
  - r-robustbase=0.99_2
  - r-rpart=4.1.23
  - r-rstatix=0.7.2
  - r-rstudioapi=0.16.0
  - r-rvest=1.0.4
  - r-sass=0.4.9
  - r-scales=1.3.0
  - r-scatterplot3d=0.3_44
  - r-selectr=0.4_2
  - r-shape=1.4.6.1
  - r-shiny=1.8.1.1
  - r-sourcetools=0.1.7_1
  - r-sp=2.1_3
  - r-sparsem=1.81
  - r-spatial=7.3_17
  - r-squarem=2021.1
  - r-stringi=1.8.3
  - r-stringr=1.5.1
  - r-survival=3.5_8
  - r-sys=3.4.2
  - r-systemfonts=1.0.5
  - r-tensora=0.36.2.1
  - r-textshaping=0.3.7
  - r-tibble=3.2.1
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.0
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-timedate=4032.109
  - r-tinytex=0.50
  - r-triebeard=0.4.1
  - r-ttr=0.24.4
  - r-tzdb=0.4.0
  - r-urltools=1.7.3
  - r-utf8=1.2.4
  - r-uuid=1.2_0
  - r-vctrs=0.6.5
  - r-viridis=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-withr=3.0.0
  - r-writexl=1.5.0
  - r-xfun=0.43
  - r-xml2=1.3.6
  - r-xtable=1.8_4
  - r-xts=0.13.2
  - r-yaml=2.3.8
  - r-zoo=1.8_12
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.34.0
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.0
  - send2trash=1.8.3
  - setuptools=69.5.1
  - sigtool=0.1.3
  - six=1.16.0
  - snappy=1.2.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.2
  - tapi=1100.0.11
  - terminado=0.18.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - tktable=2.10
  - tomli=2.0.1
  - tornado=6.4
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - uri-template=1.3.0
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - wheel=0.43.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
